import { Athiti } from "next/font/google";
import "./globals.css";

const athiti = Athiti({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Khwanjira Birthday",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className={athiti.className}>
          {children}
        </div>
      </body>
    </html>
  );
}
